apiVersion: v1
kind: Pod
metadata:
 name: postgres-pod
 labels:
   app: postgres-pod
   name: demo-voting-app
spec:
   containers:
     - name: postgres
       image: postgres:9.4
       ports:
         - containerPort: 5432