apiVersion: v1
kind: Pod
metadata:
 name: worker-app-pod
 labels:
   app: worker-app-pod
   name: demo-voting-app
spec:
   containers:
     - name: worker-app
       image: dockersamples/examplevotingapp_worker
       ports:
         - containerPort: 80